version: '3.8'

services:
  db:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "pettopia"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      interval: 2s
      retries: 15
      timeout: 2s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pettopia
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    entrypoint: >
      sh -c "./wait-for-it.sh db:3306 --timeout=90 --strict -- java -jar /app/app.jar"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: